version: "3.9"
services:
  postgres:
    container_name: films
    image: postgres
    environment:
      POSTGRES_DB: "local_db"
      POSTGRES_USER: "user1"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "7071:5432"
