#docker-compose up
version: "3.9"
services:
  deploy:
    container_name: java16app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://films:5430/local_db
      - SPRING_DATASOURCE_USERNAME=user1
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      java16-network:
        aliases:
          - java16app
networks:
  java16-network:
    name: 'our_java16_network'
